name: bluevsred2
description: Blue vs Red, Mirai!
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  adaptive_test: ^0.3.2
  audioplayers: ^3.0.0
  bloc: ^8.1.1
  equatable: ^2.0.5
  flame: ^1.6.0
  flame_audio: ^1.4.0
  flame_behaviors: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.17.0
  mockingjay: ^0.3.0

dev_dependencies:
  bloc_test: ^9.1.1
  flame_test: ^1.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Black.ttf
      - asset: fonts/Roboto-BlackItalic.ttf
      - asset: fonts/Roboto-Bold.ttf
      - asset: fonts/Roboto-BoldItalic.ttf
      - asset: fonts/Roboto-Italic.ttf
      - asset: fonts/Roboto-Light.ttf
      - asset: fonts/Roboto-LightItalic.ttf
      - asset: fonts/Roboto-Medium.ttf
      - asset: fonts/Roboto-MediumItalic.ttf
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Thin.ttf
      - asset: fonts/Roboto-ThinItalic.ttf
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Black.ttf
      - asset: fonts/Poppins-BlackItalic.ttf
      - asset: fonts/Poppins-Bold.ttf
      - asset: fonts/Poppins-BoldItalic.ttf
      - asset: fonts/Poppins-Italic.ttf
      - asset: fonts/Poppins-Light.ttf
      - asset: fonts/Poppins-LightItalic.ttf
      - asset: fonts/Poppins-Medium.ttf
      - asset: fonts/Poppins-MediumItalic.ttf
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-Thin.ttf
      - asset: fonts/Poppins-ThinItalic.ttf

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - fonts/
